export interface Language {
  code: string;
  name: string;
}

export const LANGUAGES: Language[] = [
  { code: "auto", name: "Auto-detect" },
  { code: "ar", name: "Arabic" },
  { code: "bg_BG", name: "Bulgarian" },
  { code: "bn_BD", name: "Bengali" },
  { code: "ca_ES", name: "Catalan" },
  { code: "cs_CZ", name: "Czech" },
  { code: "da_DK", name: "Danish" },
  { code: "de_DE", name: "German" },
  { code: "el_GR", name: "Greek" },
  { code: "en", name: "English" },
  { code: "es_ES", name: "Spanish" },
  { code: "et_EE", name: "Estonian" },
  { code: "fa_IR", name: "Persian" },
  { code: "fi_FI", name: "Finnish" },
  { code: "fr_FR", name: "French" },
  { code: "gl_ES", name: "Galician" },
  { code: "gu_IN", name: "Gujarati" },
  { code: "he_IL", name: "Hebrew" },
  { code: "hi_IN", name: "Hindi" },
  { code: "hr_HR", name: "Croatian" },
  { code: "hu_HU", name: "Hungarian" },
  { code: "id_ID", name: "Indonesian" },
  { code: "it_IT", name: "Italian" },
  { code: "ja_JP", name: "Japanese" },
  { code: "kn_IN", name: "Kannada" },
  { code: "ko_KR", name: "Korean" },
  { code: "lt_LT", name: "Lithuanian" },
  { code: "lv_LV", name: "Latvian" },
  { code: "mk_MK", name: "Macedonian" },
  { code: "ml_IN", name: "Malayalam" },
  { code: "mr_IN", name: "Marathi" },
  { code: "ms_MY", name: "Malay" },
  { code: "mt_MT", name: "Maltese" },
  { code: "nl_NL", name: "Dutch" },
  { code: "no_NO", name: "Norwegian" },
  { code: "pl_PL", name: "Polish" },
  { code: "pt_BR", name: "Portuguese (Brazil)" },
  { code: "pt_PT", name: "Portuguese (Portugal)" },
  { code: "ro_RO", name: "Romanian" },
  { code: "ru_RU", name: "Russian" },
  { code: "sk_SK", name: "Slovak" },
  { code: "sl_SI", name: "Slovenian" },
  { code: "sq_AL", name: "Albanian" },
  { code: "sr_RS", name: "Serbian" },
  { code: "sv_SE", name: "Swedish" },
  { code: "sw", name: "Swahili" },
  { code: "ta_IN", name: "Tamil" },
  { code: "te_IN", name: "Telugu" },
  { code: "th_TH", name: "Thai" },
  { code: "tr_TR", name: "Turkish" },
  { code: "uk_UA", name: "Ukrainian" },
  { code: "ur_PK", name: "Urdu" },
  { code: "vi_VN", name: "Vietnamese" },
  { code: "zh_CN", name: "Chinese (Simplified)" },
  { code: "zh_TW", name: "Chinese (Traditional)" },
];

export const SOURCE_LANGUAGES = LANGUAGES;
export const TARGET_LANGUAGES = LANGUAGES.filter((l) => l.code !== "auto");
